# Generated by Django 4.2.7 on 2023-12-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeend',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestart',
            field=models.CharField(max_length=7),
        ),
    ]
