# Generated by Django 4.2.7 on 2023-12-03 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrackerapp', '0002_alter_task_timeend_alter_task_timestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
