# Generated by Django 4.2.7 on 2023-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrackerapp', '0003_alter_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(max_length=200),
        ),
    ]
